export const WeatherTypes = {
	Blizzard: 'BLIZZARD',
	Clear: 'CLEAR',
	Clearing: 'CLEARING',
	Clouds: 'CLOUDS',
	ExtraSunny: 'EXTRASUNNY',
	Foggy: 'FOGGY',
	Neutral: 'NEUTRAL',
	Overcast: 'OVERCAST',
	Rain: 'RAIN',
	Smog: 'SMOG',
	Snow: 'SNOW',
	SnowLight: 'SNOWLIGHT',
	Thunder: 'THUNDER',
	Wind: 'WIND',
	Xmas: 'XMAS',
};
